dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.5
  shared_preferences: ^2.0.15
  provider: ^6.0.3
  path_provider: ^2.0.11
  flutter_svg: ^1.1.6
  intl: ^0.17.0
  flutter_reanimated: ^2.3.0
  url_launcher: ^6.1.10
  flutter_markdown: ^0.6.14
  flutter_colorpicker: ^1.0.3
  flutter_inappwebview: ^5.7.2+3
  package_info_plus: ^3.0.3